# Generated by Django 3.2.3 on 2021-06-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_account', models.CharField(max_length=30, unique=True)),
                ('User_password', models.CharField(max_length=20)),
                ('User_name', models.CharField(max_length=20)),
                ('User_number', models.CharField(max_length=20, unique=True)),
                ('User_post', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_useraccount', models.CharField(max_length=30, unique=True)),
                ('Job_flag', models.IntegerField(choices=[(1, '已完成任务'), (2, '主任务'), (3, '子任务'), (4, '下阶段任务')])),
                ('Job_name', models.CharField(max_length=30, unique=True)),
                ('Job_finish_date', models.IntegerField()),
                ('Job_begin_date', models.IntegerField()),
                ('Job_over_date', models.IntegerField()),
                ('Job_level', models.IntegerField(choices=[(1, '5%'), (2, '10%'), (3, '15%'), (4, '20%'), (5, '25%'), (6, '30%'), (7, '35%'), (8, '40%'), (9, '45%'), (10, '50%'), (11, '55%'), (12, '60%'), (13, '65%'), (14, '70%'), (15, '75%'), (16, '80%'), (17, '85%'), (18, '90%'), (19, '95%'), (20, '100%')])),
                ('Job_introduce', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job_Log_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Main_useraccount', models.CharField(max_length=30, unique=True)),
                ('Main_name', models.CharField(max_length=30, unique=True)),
                ('Main_finish_date', models.IntegerField()),
                ('Main_level', models.IntegerField(choices=[(1, '5%'), (2, '10%'), (3, '15%'), (4, '20%'), (5, '25%'), (6, '30%'), (7, '35%'), (8, '40%'), (9, '45%'), (10, '50%'), (11, '55%'), (12, '60%'), (13, '65%'), (14, '70%'), (15, '75%'), (16, '80%'), (17, '85%'), (18, '90%'), (19, '95%'), (20, '100%')])),
                ('Main_introduce', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job_Log_Next',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Next_useraccount', models.CharField(max_length=30, unique=True)),
                ('Next_name', models.CharField(max_length=30, unique=True)),
                ('Next_begin_date', models.IntegerField()),
                ('Next_introduce', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job_Log_Secondly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Secondly_useraccount', models.CharField(max_length=30, unique=True)),
                ('Secondly_name', models.CharField(max_length=30, unique=True)),
                ('Secondly_finish_date', models.IntegerField()),
                ('Secondly_level', models.IntegerField(choices=[(1, '5%'), (2, '10%'), (3, '15%'), (4, '20%'), (5, '25%'), (6, '30%'), (7, '35%'), (8, '40%'), (9, '45%'), (10, '50%'), (11, '55%'), (12, '60%'), (13, '65%'), (14, '70%'), (15, '75%'), (16, '80%'), (17, '85%'), (18, '90%'), (19, '95%'), (20, '100%')])),
                ('Secondly_introduce', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job_Milepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Milepost_date', models.IntegerField()),
                ('Milepost_content', models.TextField()),
            ],
        ),
    ]
